### 
POST http://localhost:3000/api/payments
Content-Type: application/json

{
        "totalAmount": 123,
        "referenceYear": 2023,
        "paymentStatus": "unpaid",
        "referenceMonth": 6,
        "affiliateId": "eade7e58-75c6-4b0b-ac92-b01afb510f93"
}

### 
GET http://localhost:3000/api/payments/consecutive
Content-Type: application/json

{
        "id": "c5df2f8e-f7ec-4e8f-a545-1fecfd1b2d14"
}

###
GET http://localhost:3000/api/affiliates/unpaids


###
PUT http://localhost:3000/api/affiliates/deactivateSome
Content-Type: application/json

{
        "dnis": [111, 222]
}



###
GET http://localhost:3000/api/affiliates/mails
Content-Type: application/json

{
        "dnis": [111, 222, 333, 444]
}


###
GET http://localhost:3000/api/affiliates/verifyUnpaidMonths


###
GET http://localhost:3000/api/affiliates/affiliatesInDebt

###
GET http://localhost:3000/api/affiliates/affiliate-status/44907383