### 
POST http://localhost:3000/api/payments
Content-Type: application/json

{
        "totalAmount": 123,
        "referenceYear": 2024,
        "referenceMonth": 6,
        "affiliateId": "7199d78c-0bbf-4c90-88d8-7c6fc85e5c12"
}

### 
GET http://localhost:3000/api/payments/consecutive
Content-Type: application/json

{
        "id": "7699d18c-0bbf-4c10-88d8-7c6fc85e5c10"
}

###
GET http://localhost:3000/api/affiliates/unpaids


###
PUT http://localhost:3000/api/affiliates/deactivateSome
Content-Type: application/json

{
        "dnis": [111, 222]
}



###
GET http://localhost:3000/api/affiliates/mails
Content-Type: application/json

{
        "dnis": [111, 222, 333, 444]
}


###
GET http://localhost:3000/api/affiliates/verifyUnpaidMonths