### 
POST http://localhost:3000/api/payments
Content-Type: application/json

{
        "totalAmount": 123,
        "referenceYear": 2023,
        "paymentStatus": "unpaid",
        "referenceMonth": 6,
        "affiliateId": "b8fcdedd-707f-4cc3-9162-2a8946593640"
}

### 
GET http://localhost:3000/api/payments/consecutive
Content-Type: application/json

{
        "id": "b8fcdedd-707f-4cc3-9162-2a8946593640"
}

###
GET http://localhost:3000/api/affiliates/unpaids


###
PUT http://localhost:3000/api/affiliates/deactivateSome
Content-Type: application/json

{
        "dnis": [111, 222]
}



###
GET http://localhost:3000/api/affiliates/mails
Content-Type: application/json

{
        "dnis": [111, 222, 333, 444]
}


###
GET http://localhost:3000/api/affiliates/verifyUnpaidMonths


###
GET http://localhost:3000/api/affiliates/affiliatesInDebt

###
GET http://localhost:3000/api/affiliates/affiliate-status/44907383